# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PetFeeder' do
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Database', '~> 5.20.1'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTImage',
    'CxxBridge', 
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  pod 'Folly', :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'lottie-ios', :path => '../node_modules/lottie-ios'

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end
end
